In [1]:
import numpy as np

In [2]:
grid = [[0,8,0,6,4,0,0,0,7],
        [7,6,0,5,3,0,9,0,0],
        [0,0,0,0,2,7,0,0,3],
        [1,4,0,9,6,2,0,7,0],
        [2,0,0,3,7,0,0,0,1],
        [0,7,0,0,8,0,4,2,9],
        [5,1,0,0,9,6,8,0,0],
        [0,0,0,0,0,8,7,0,5],
        [0,0,0,7,0,0,0,9,6]]

In [3]:
def possible(row, column, number):
    global grid
    for i in range (0,9):
        if grid[row][i] == number:
            return False
    for i in range (0,9):    
        if grid[i][column] == number:
            return False
    x0 = (column // 3) * 3
    y0 = (row // 3) * 3
    for i in range(0,3):
        for j in range(0,3):
            if grid[y0+i][x0+j] == number:
                return False
    return True
def solve():
    global grid
    for row in range(0,9):
        for column in range(0,9):
            if grid[row][column] == 0:
                for number in range (1,10):
                    if possible(row, column, number):
                        grid[row][column] = number
                        solve()
                        grid[row][column] = 0
                return
    print(np.matrix(grid))
    input("More possible sollutions")
solve()

[[3 8 1 6 4 9 2 5 7]
 [7 6 2 5 3 1 9 8 4]
 [4 5 9 8 2 7 6 1 3]
 [1 4 5 9 6 2 3 7 8]
 [2 9 8 3 7 4 5 6 1]
 [6 7 3 1 8 5 4 2 9]
 [5 1 7 4 9 6 8 3 2]
 [9 3 6 2 1 8 7 4 5]
 [8 2 4 7 5 3 1 9 6]]
More possible sollutions
